language: r
cache: packages

before_install:
  - sudo apt-get install -y latexmk

script: make book

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

