language: r
r_packages:
  - magrittr
  - tidyverse

cache: packages
sudo: required
services: docker

script:
  - make cleanall
  - make book
  - docker run --mount src=$TRAVIS_BUILD_DIR/build,target=/usr/src/tex,type=bind dxjoke/tectonic-docker /bin/sh -c "tectonic book.tex"
  - make copybook
  - make cleanall

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master

